POST http://localhost:3000/updateProgress
Content-Type: application/json

{
    "email" : "ksh2707@gmail.com",
    "text"  : "Streams",
    "status" : 1
}

###

POST http://localhost:3000/progress
Content-Type: application/json

{
    "email" : "ksh2707@gmail.com",
    "text"  : "Ant"
}
###
POST http://localhost:3000/userProgress
Content-Type: application/json

{
    "email" : "ksh2707@gmail.com"
}